// <auto-generated />
namespace TwoStu.Logic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newt));
        
        string IMigrationMetadata.Id
        {
            get { return "201701251655560_newt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
